# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Setup
title:               braindeadpool
tagline:             'personal webpage'
description:         'braindeadpool!'
url:                 http://www.braindeadpool.com
baseurl:             
paginate:            5

# About/contact
author:
  name:              Bruce Wilson
  url:               https://twitter.com/braindeadpool
  email:             brain.deadpool@gmail.com

# Custom vars
version:             1.0.0

# Plugins
gems:      [jekyll-paginate]
