# Permalinks
#
permalink:           pretty

# Setup
title:               braindeadpool
tagline:             'personal webpage'
description:         'braindeadpool!'
url:                 http://www.braindeadpool.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Bruce Wilson
  url:               https://twitter.com/braindeadpool
  email:             brain.deadpool@gmail.com

# Custom vars
version:             1.0.0
