# Permalinks
#
permalink:           pretty

# Setup
title:               BrainDeadpool
tagline:             'Personal webpage'
description:         'Jekyll design by http://lanyon.getpoole.com'
url:                 http://www.braindeadpool.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Bruce Wilson
  url:               https://twitter.com/braindeadpool
  email:             braindeadpool@gmail.com

# Custom vars
version:             1.0.0
